// Standalone benchmark: AsyncLLMClient against a live vLLM-style endpoint.
//
// Two modes:
//   (1) Synthetic mode (default): a tiny canned chat payload, useful to
//       measure the dispatcher's raw network ceiling.
//   (2) Replay mode (--payload-file): cycle through a JSONL of pre-built
//       payloads (e.g. generated by tools/generate_e1_payloads.py). The wire
//       bytes are identical to what sembench's vllm_perf_driver.py sends, so
//       throughput is directly comparable to a real E1/E5 cell's
//       throughput_rows_per_s.
//
// Reports throughput_requests_per_s + (if --rows-per-request set) rows/s.
//
// Usage:
//   flock_async_bench --endpoint http://127.0.0.1:8000/v1/chat/completions
//                     --inflight 128 --total 4096
//
//   flock_async_bench --endpoint http://127.0.0.1:8000/v1/completions
//                     --payload-file /tmp/e1_payloads.jsonl
//                     --inflight 128 --total 1000 --warmup 128
//                     --rows-per-request 32 --timeout-ms 120000

#include "flock/runtime/async_llm_client.h"

#include <atomic>
#include <chrono>
#include <condition_variable>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <mutex>
#include <string>
#include <thread>
#include <vector>

namespace {

struct Args {
    std::string endpoint = "http://127.0.0.1:8000/v1/chat/completions";
    std::string model = "Qwen/Qwen2.5-7B-Instruct";
    int inflight = 128;
    int total = 4096;
    int warmup = 0;
    int max_tokens = 32;
    int rows_per_request = 1;
    int timeout_ms = 60000;
    std::string payload_file;
};

void Usage(const char* prog) {
    std::fprintf(stderr,
                 "Usage: %s [--endpoint URL] [--model NAME] [--inflight N]\n"
                 "          [--total N] [--warmup N] [--max-tokens N]\n"
                 "          [--rows-per-request N] [--timeout-ms N]\n"
                 "          [--payload-file PATH]\n",
                 prog);
}

bool ParseArgs(int argc, char** argv, Args* a) {
    for (int i = 1; i < argc; ++i) {
        const char* k = argv[i];
        auto need = [&](const char* name) {
            if (i + 1 >= argc) {
                std::fprintf(stderr, "missing value for %s\n", name);
                std::exit(2);
            }
            return argv[++i];
        };
        if (!std::strcmp(k, "--endpoint")) a->endpoint = need("--endpoint");
        else if (!std::strcmp(k, "--model")) a->model = need("--model");
        else if (!std::strcmp(k, "--inflight")) a->inflight = std::atoi(need("--inflight"));
        else if (!std::strcmp(k, "--total")) a->total = std::atoi(need("--total"));
        else if (!std::strcmp(k, "--warmup")) a->warmup = std::atoi(need("--warmup"));
        else if (!std::strcmp(k, "--max-tokens")) a->max_tokens = std::atoi(need("--max-tokens"));
        else if (!std::strcmp(k, "--rows-per-request")) a->rows_per_request = std::atoi(need("--rows-per-request"));
        else if (!std::strcmp(k, "--timeout-ms")) a->timeout_ms = std::atoi(need("--timeout-ms"));
        else if (!std::strcmp(k, "--payload-file")) a->payload_file = need("--payload-file");
        else if (!std::strcmp(k, "-h") || !std::strcmp(k, "--help")) {
            Usage(argv[0]);
            return false;
        } else {
            std::fprintf(stderr, "unknown arg: %s\n", k);
            Usage(argv[0]);
            return false;
        }
    }
    if (a->inflight <= 0 || a->total <= 0) {
        std::fprintf(stderr, "inflight and total must be positive\n");
        return false;
    }
    return true;
}

std::string BuildSyntheticPayload(const Args& a) {
    std::string p;
    p += "{\"model\":\"";
    p += a.model;
    p += "\",\"messages\":[{\"role\":\"user\",\"content\":\"Reply with the single word YES.\"}]";
    p += ",\"max_tokens\":";
    p += std::to_string(a.max_tokens);
    p += ",\"temperature\":0}";
    return p;
}

std::vector<std::string> LoadPayloads(const std::string& path) {
    std::ifstream in(path);
    if (!in) {
        std::fprintf(stderr, "cannot open payload file: %s\n", path.c_str());
        std::exit(1);
    }
    std::vector<std::string> out;
    std::string line;
    while (std::getline(in, line)) {
        if (!line.empty()) out.push_back(std::move(line));
    }
    if (out.empty()) {
        std::fprintf(stderr, "payload file is empty: %s\n", path.c_str());
        std::exit(1);
    }
    return out;
}

struct Stats {
    std::atomic<int> outstanding{0};
    std::atomic<int> completed{0};
    std::atomic<int> ok{0};
    std::atomic<int> err{0};
    std::atomic<int64_t> sum_latency_us{0};
    std::atomic<int64_t> max_latency_us{0};
};

void RunPhase(flock::AsyncLLMClient& client,
              const Args& args,
              const std::vector<std::string>& payloads,
              const std::string& rid_prefix,
              int count,
              Stats& stats,
              const char* phase_name) {
    std::mutex slot_mu;
    std::condition_variable slot_cv;

    auto on_done = [&](flock::AsyncLLMClient::Response r) {
        if (r.ok) stats.ok.fetch_add(1, std::memory_order_relaxed);
        else stats.err.fetch_add(1, std::memory_order_relaxed);
        stats.sum_latency_us.fetch_add(r.latency_us, std::memory_order_relaxed);
        int64_t prev = stats.max_latency_us.load(std::memory_order_relaxed);
        while (r.latency_us > prev &&
               !stats.max_latency_us.compare_exchange_weak(prev, r.latency_us,
                                                          std::memory_order_relaxed)) {}
        stats.outstanding.fetch_sub(1, std::memory_order_relaxed);
        stats.completed.fetch_add(1, std::memory_order_relaxed);
        {
            std::lock_guard<std::mutex> lock(slot_mu);
        }
        slot_cv.notify_all();
    };

    const int start_completed = stats.completed.load();
    auto t0 = std::chrono::steady_clock::now();
    auto last_report = t0;
    int last_completed = start_completed;

    for (int i = 0; i < count; ++i) {
        {
            std::unique_lock<std::mutex> lock(slot_mu);
            slot_cv.wait(lock, [&] {
                return stats.outstanding.load(std::memory_order_relaxed) < args.inflight;
            });
        }
        stats.outstanding.fetch_add(1, std::memory_order_relaxed);
        const std::string& payload =
            payloads.empty() ? "" : payloads[i % payloads.size()];
        client.Submit(args.endpoint, payload, /*generation=*/1,
                      rid_prefix + std::to_string(i), on_done);

        auto now = std::chrono::steady_clock::now();
        if (now - last_report >= std::chrono::seconds(2)) {
            int c = stats.completed.load(std::memory_order_relaxed);
            double dt = std::chrono::duration<double>(now - last_report).count();
            double rps = (c - last_completed) / dt;
            std::fprintf(stderr,
                         "  [%s] submitted=%d completed=%d inflight=%d rate=%.1f req/s\n",
                         phase_name, i + 1, c - start_completed,
                         stats.outstanding.load(), rps);
            last_completed = c;
            last_report = now;
        }
    }

    // Drain.
    {
        std::unique_lock<std::mutex> lock(slot_mu);
        slot_cv.wait(lock, [&] {
            return stats.completed.load(std::memory_order_relaxed) >=
                   start_completed + count;
        });
    }
    auto t1 = std::chrono::steady_clock::now();
    double dt = std::chrono::duration<double>(t1 - t0).count();
    std::fprintf(stderr, "  [%s] done: %d req in %.2fs = %.2f req/s\n",
                 phase_name, count, dt, count / dt);
}

}  // namespace

int main(int argc, char** argv) {
    Args args;
    if (!ParseArgs(argc, argv, &args)) return 2;

    std::vector<std::string> payloads;
    if (!args.payload_file.empty()) {
        payloads = LoadPayloads(args.payload_file);
        std::fprintf(stderr, "loaded %zu payloads from %s\n",
                     payloads.size(), args.payload_file.c_str());
    } else {
        payloads.push_back(BuildSyntheticPayload(args));
    }

    flock::AsyncLLMClient::Options opts;
    opts.request_timeout_ms = args.timeout_ms;
    flock::AsyncLLMClient client(opts);

    std::fprintf(stderr,
                 "endpoint=%s inflight=%d warmup=%d total=%d timeout_ms=%d "
                 "rows_per_request=%d payloads=%zu\n",
                 args.endpoint.c_str(), args.inflight, args.warmup,
                 args.total, args.timeout_ms, args.rows_per_request,
                 payloads.size());

    Stats warm_stats;
    if (args.warmup > 0) {
        RunPhase(client, args, payloads, "warm-", args.warmup, warm_stats, "warmup");
    }

    Stats stats;
    auto t0 = std::chrono::steady_clock::now();
    RunPhase(client, args, payloads, "main-", args.total, stats, "main");
    auto t1 = std::chrono::steady_clock::now();

    double elapsed_s = std::chrono::duration<double>(t1 - t0).count();
    int ok = stats.ok.load();
    int err = stats.err.load();
    double req_s = args.total / elapsed_s;
    double rows_s = ok * args.rows_per_request / elapsed_s;
    double mean_lat_ms = stats.sum_latency_us.load() / 1000.0 / args.total;
    double max_lat_ms = stats.max_latency_us.load() / 1000.0;

    std::printf("MAIN total=%d ok=%d err=%d elapsed_s=%.3f "
                "throughput_requests_per_s=%.4f throughput_rows_per_s=%.4f "
                "mean_latency_ms=%.2f max_latency_ms=%.2f\n",
                args.total, ok, err, elapsed_s,
                req_s, rows_s, mean_lat_ms, max_lat_ms);
    return err == 0 ? 0 : 1;
}
